mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: mqduong+1@amazon.com
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: mqduong+3@amazon.com
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: mqduong+2@amazon.com
    organizationalUnit: Security
    warm: false

workloadAccounts:
  - name: Network-Suspended
    description: Suspended Network account
    email: mqduong+4@amazon.com
    organizationalUnit: Suspended
    warm: true
  - name: Network
    description: Network account for VPC endpoints
    email: mqduong+5@amazon.com
    organizationalUnit: Infrastructure
    warm: false