transitGateways: []
endpointPolicies:
  - name: Default
    document: policy-documents/vpc-endpoint-default-policy.json
defaultVpc:
  delete: false
  excludeAccounts: []

vpcs:
  - name: core-shared-endpoint
    account: Management
    region: us-east-1
    cidrs:
      - 10.0.0.0/24
    enableDnsHostnames: true
    enableDnsSupport: true
    internetGateway: false
    subnets:
      - name: subnet-1
        availabilityZone: a
        ipv4CidrBlock: 10.0.0.0/26
      - name: subnet-2
        availabilityZone: b
        ipv4CidrBlock: 10.0.0.64/26
    interfaceEndpoints:
      central: true
      defaultPolicy: Default
      subnets:
        - subnet-1
        - subnet-2
      endpoints:
        - service: ec2

  - name: public-shared-endpoint
    account: Management
    region: us-east-1
    cidrs:
      - 10.1.0.0/24
    enableDnsHostnames: true
    enableDnsSupport: true
    internetGateway: false
    subnets:
      - name: subnet-1
        availabilityZone: a
        ipv4CidrBlock: 10.1.0.0/26
      - name: subnet-2
        availabilityZone: b
        ipv4CidrBlock: 10.1.0.64/26
    interfaceEndpoints:
      central: false
      defaultPolicy: Default
      subnets:
        - subnet-1
        - subnet-2
      endpoints:
        - service: ec2
