transitGateways: []
endpointPolicies: []
defaultVpc:
  delete: false
  excludeAccounts: []

vpcs:
  - name: core-shared-endpoint
    account: Network
    region: us-east-1
    cidrs:
      - 10.251.0.0/24
    enableDnsHostnames: true
    enableDnsSupport: true
    internetGateway: false
    subnets:
      - name: VPCe-subnet-1
        availabilityZone: a
        ipv4CidrBlock: 10.251.0.0/26
      - name: VPCe-subnet-2
        availabilityZone: b
        ipv4CidrBlock: 10.251.0.64/26
    interfaceEndpoints:
      central: true
      subnets:
        - VPCe-subnet-1
        - VPCe-subnet-2
      endpoints:
        - service: ssm

  - name: public-shared-endpoint
    account: Network
    region: us-east-1
    cidrs:
      - 10.252.0.0/24
    enableDnsHostnames: true
    enableDnsSupport: true
    internetGateway: false
    subnets:
      - name: VPCe-subnet-1
        availabilityZone: a
        ipv4CidrBlock: 10.252.0.0/26
      - name: VPCe-subnet-2
        availabilityZone: b
        ipv4CidrBlock: 10.252.0.64/26
    interfaceEndpoints:
      central: false
      subnets:
        - VPCe-subnet-1
        - VPCe-subnet-2
      endpoints:
        - service: ssm
